#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Get staged files to check with prettier.
files=$(git diff --cached --name-only --diff-filter=ACM | grep -E '\.(js|jsx|ts|tsx|json)$' || true)

# Check if there are any files to format
if [ -n "$files" ]; then
  echo "Checking formatting for: $files"
  yarn prettier --check $files
else
  echo "No matching files to check."
fi
