name: Tests
on:
  push:
    branches: ["main", "develop"]
  pull_request:
    branches: ["main", "develop"]

jobs:
  # jest-run:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v4

  #     - name: Set up Node.js
  #       uses: actions/setup-node@v4
  #       with:
  #         node-version: "16"
  #         cache: "yarn"

  #     - name: Install packages
  #       run: yarn install --frozen-lockfile && yarn add "https://github.com/zimmerman-team/rawgraphs-charts.git#0fc0c9d"

  #     - name: Build rawgraphs package
  #       run: |
  #         if [ -d "node_modules/@rawgraphs/rawgraphs-charts" ]; then
  #           cd node_modules/@rawgraphs/rawgraphs-charts
  #           yarn
  #           yarn build
  #         else
  #           echo "Package directory not found"
  #         fi

  #     - name: Jest run
  #       run: yarn test

  cypress-run:
    runs-on: [self-hosted, cypress]
    steps:
      - name: Checkout to current branch
        run: |
          cd ~/DX
          cd dx.client
          git fetch origin
          git checkout ${{ github.head_ref }}
          git pull origin ${{ github.head_ref }}

      - name: Build yarn
        run: |
          cd ~/DX
          cd dx.client
          yarn install

      - name: Run app with pm2
        run: |
          cd ~/DX
          cd dx.client
          pm2 start yarn --name "dx.client" -- start

      - name: Wait for app to be ready
        run: |
          cd ~/DX
          cd dx.client
          while ! curl -s -f -o /dev/null http://localhost:3000; do sleep 5; done
          echo "App is ready"

      - name: Cypress run
        # Uses the official Cypress GitHub action https://github.com/cypress-io/github-action
        run: |
          cd ~/DX
          cd dx.client
          npx cypress run --record --key $CYPRESS_RECORD_KEY

      - name: Stop pm2
        run: |
          cd ~/DX
          cd dx.client
          pm2 stop dx.client
          pm2 delete dx.client
